.commitlintrc.yml
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.husky/commit-msg
.husky/pre-commit
.prettierrc.yml
.solhint.json
CONTRIBUTING.md
package.json
test/Reserve.t.sol
yarn.lock

Added guidelines for contributing to the repository along with the following:
- Added issue templates for bug reports and feature requests
- Set up husky and added checks for commit messages
None
N/A
N/A
N/A
N/A

chore: add contribution guidelines & rules

---

.prettierrc.yml
test/StableTokenRegistry.t.sol

Migrating StableTokenRegistry tests to foundry

stableTokenRegistry tests in Foundry

---

contracts/BiPoolManager.sol
contracts/Reserve.sol
contracts/interfaces/IBiPoolManager.sol
contracts/interfaces/IReserve.sol
test/BiPoolManager.t.sol
test/Reserve.t.sol
test/integration/BrokerIntegration.t.sol
test/utils/McMintIntegration.sol
test/utils/Token.sol
test/utils/WithRegistry.sol

Add integration tests tying all McMint related work together.
Things to test:
N/A
It is tests
- Fixes https://github.com/mento-protocol/mento-general/issues/43
N/A
N/A

test: add broker integration tests

---

.github/workflows/ci.yml

Adds slither analyzer to the CI workflow
None
Tested in PR.
- Fixes #40 
N/A
N/A

chore: add slither action

---

README.md

I wanted to emphasise that our reserve is over collateralized
N/A

chore: update description of mento

---

.github/workflows/ci.yml

Temporarily remove slither to look into foundry support.
- Fixes #48

ci: remove slither

---

.github/workflows/ci.yml

Temporarily remove job to check linked issue as it was flakey. Will look into re-adding. 
Tested in this PR
- Fixes #46

ci: remove flakey issue check

---

test/integration/BrokerIntegration.t.sol

found and deleted a couple of unused lines of code
-
- yes, integration tests work fine 
-
- fully
-

feat(test): delete unused code

---

CONTRIBUTING.md

Documenting our naming conventions for git branches and commit messages

feat(contributions): update naming conventions

---

contracts/BiPoolManager.sol

Removes duplicate interface declaration
None
- Unit tests run and pass as before
- Closes #102 
N/A
N/A

fix: remove duplicate interface

---

contracts/BiPoolManager.sol
contracts/BreakerBox.sol
contracts/Broker.sol
contracts/Reserve.sol

- Uses safe math for some operations.
- Removed unneeded todo's & comment
- Ran existing tests to confirm contracts function as they should
- Closes [#14](https://github.com/mento-protocol/mento-general/issues/141)
N/A
N/A

fix: use safemath for arithmetic operations

---

contracts/BiPoolManager.sol

- added the missing natspec comment 
- N/A
- N/A
- Fixes https://github.com/mento-protocol/mento-general/issues/155
- N/A
- N/A

style: add missing NatSpec comments

---

package.json

Update package name in package.json
N/A
N/A
- Closes #145 
N/A
N/A

fix: update package name

---

.github/workflows/ci.yml

- check out [this PR](https://github.com/mento-protocol/mento-core/pull/158) for a detailed description 
- I am adding those changes also to main to make sure that once we merge develop into main we see which storage changes were made to the production version of Mento
- N/A
N/A
- Fixes #157 
- N/A
-N/A

feat: add jobs to ci

---

contracts/Reserve.sol
contracts/interfaces/IReserve.sol
test/Reserve.t.sol

The changes in [f7b79d0](https://github.com/celo-org/celo-monorepo/commit/f7b79d0a15ba1e783fa30db948b94c4b932c92a4) were mistakenly added to the main branch and do not reflect the protocol as it is currently deployed. This change removes the additional code that was added to the reserve smart contract and tests.
- N/A
- Ran existing test suite to verify functionality works.
- Closes #168 
- N/A
- N/A

Revert "gigamento changes reserve.sol"

---

contracts/BreakerBox.sol
test/BreakerBox.t.sol

Self-explanatory.
N/A
N/A
N/A
N/A
N/A

Fix function casing

---

contracts/ConstantProductPricingModule.sol

Fixed a math comment 
No
No, only comment
No issue
Fully, only comment
it's the documentation :P

docs(constantProductPricing): feature/fixConstantProductComment

---

test/fork-tests/BaseForkTest.t.sol
test/fork-tests/TestAsserts.t.sol
test/fork-tests/Utils.t.sol

Some of the fork tests and related utils also suffered from bad decimal comprehension. 
This PR fixes these shortcomings.
N/A
Ran on Alfajores and Baklava
- https://github.com/mento-protocol/mento-deployment/issues/45
It's an extension
N/A

hotfix: Fork Test Decimal issues 

---

contracts/legacy/StableToken.sol

A variable was not included, so it was added.

Added missing natspec variable to StableToken.sol

---

contracts/oracles/SortedOracles.sol

fix: typo in sortedoracles

---

test/oracles/SortedOracles.t.sol

refactor: move & rename test

---

contracts/legacy/proxies/ExchangeBRLProxy.sol
contracts/legacy/proxies/ExchangeEURProxy.sol
contracts/legacy/proxies/ExchangeProxy.sol
contracts/legacy/proxies/GrandaMentoProxy.sol
contracts/legacy/proxies/ReserveSpenderMultiSigProxy.sol
contracts/legacy/proxies/StableTokenBRLProxy.sol
contracts/legacy/proxies/StableTokenEURProxy.sol
contracts/legacy/proxies/StableTokenProxy.sol
contracts/legacy/proxies/StableTokenXOFProxy.sol
contracts/oracles/breakers/MedianDeltaBreaker.sol

- made non-relative imports relative to avoid errors in deployment repo 
- typo in MedianDeltaBreaker import
- Fixes #234

chore: update non relative imports

---

contracts/swap/BiPoolManager.sol

Use return values in the function declaration
n/a
n/a
- Fixes #250 
n/a
n/a

feat: use return values in the function declaration

---

test/fork-tests/BaseForkTest.t.sol
test/fork-tests/TestAsserts.t.sol
test/fork-tests/Utils.t.sol

Merging this into main as it's the last piece of code related to MU03.
┆Issue is synchronized with this [Jira Story](https://mentolabs.atlassian.net/browse/MC-7) by [Unito](https://www.unito.io)

fix: outdated fork-tests after MU03 (#264)

---

test/fork-tests/BaseForkTest.t.sol
test/fork-tests/TestAsserts.t.sol

Fixes broken fork tests after MU05
1- Included MockNativeUSDC in the test setup to fund reserve for tests
2- Added a check to prevent the test going into infinite loop for native USDC swaps
Fork tests are green on baklava

fix: fork tests

---

contracts/governance/GovernanceFactory.sol

Fixes #381 from [audit finding Q-2](https://www.notion.so/0xmacro/Mento-3-Preliminary-Audit-Report-external-private-06ee6ce11d7d4df0a950ca97c75a2766?pvs=4#f7f7efa843ca4e18b86c1642dfc4939e)

fix(GovernanceFactory): added missing assert on MentoGovernor deployment

---

contracts/governance/locking/Locking.sol
contracts/governance/locking/LockingBase.sol
contracts/governance/locking/LockingRelock.sol
contracts/governance/locking/libs/LibBrokenLine.sol
test/governance/IntegrationTests/GovernanceIntegration.gas.t.sol
test/governance/IntegrationTests/LockingIntegration.fuzz.t.sol
test/governance/Locking/Locking.fuzz.t.sol
test/governance/Locking/delegateTo.t.sol
test/governance/Locking/locking.t.sol
test/governance/Locking/relock.t.sol

Fixes for sherlock contest findings are signed off by the LSW. We can merge the changes into develop now

Merge fixes of contest findings

---

contracts/legacy/proxies/StableTokenCOPProxy.sol
contracts/legacy/proxies/StableTokenKESProxy.sol

- Adds proxy contracts for cCOP & cKES
- None
- N/A - No new functionality or changes to existing
- Fixes https://github.com/mento-protocol/mento-deployment/issues/174
- N/A
- N/A

feat: add COP and KES proxy contracts

---

test/fork-tests/BaseForkTest.t.sol
test/utils/TokenHelpers.t.sol

- adds cKES to our fork-test 
- as of now only works on baklava since proposal has only been executed on baklava

feat: add cKES to fork-tests

---

contracts/legacy/proxies/StableTokenINRProxy.sol

adds the proxy contract for the cINR

feat: add cINR proxy contract

---

contracts/legacy/proxies/StableTokenPHPProxy.sol

feat: add cPHP proxy contract

---

contracts/legacy/proxies/StableTokenPSOProxy.sol

adds the PSO Proxy contract + removes PHP

feat: add PUSO + remove cPHP proxy contract

---

package.json
test/fork/ForkTests.t.sol

Tests are green on mainnet
> Ran 16 test suites in 198.84s (1737.74s CPU time): 218 tests passed, 0 failed, 0 skipped (218 total tests)
✨  Done in 199.84s.

chore: add mainnet php/usd fork tests

---

contracts/goodDollar/GoodDollarExchangeProvider.sol
contracts/goodDollar/GoodDollarExpansionController.sol
contracts/interfaces/IGoodDollarExchangeProvider.sol
test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
test/unit/goodDollar/GoodDollarExpansionController.t.sol
test/utils/harnesses/GoodDollarExpansionControllerHarness.sol

This PR adds additional tests to to the exchange provider and includes fuzz testing
- Fixes https://github.com/mento-protocol/mento-general/issues/454
-

Feat(454): Exchange provider tests 

---

contracts/tokens/StableTokenGHSProxy.sol

Adds the proxy for GHS which will be used for both cGHS(pilot) and the actual cGHS in future
no
- https://github.com/mento-protocol/mento-general/issues/576

Feat add stable tokenc ghs proxy

---

contracts/interfaces/IReserve.sol

- this PR adds a missing getter from the reserve contract to the interfaces

chore: add missing getter function from Reserve to interface

---

contracts/libraries/TradingLimits.sol
test/unit/libraries/TradingLimits.t.sol

Fixes the audit finding https://audits.sherlock.xyz/contests/598/voting/44?dashboard_id=14327c9c7bc843a43c46c4efd899f4c1
no
Unit test
- Fixes [#597](https://github.com/mento-protocol/mento-general/issues/597)

feat: fix add missing min check

---

.github/workflows/storage-layout.yaml
contracts/governance/deployers/LockingDeployerLib.sol
contracts/governance/locking/Locking.sol
contracts/governance/locking/LockingBase.sol
contracts/governance/locking/LockingRelock.sol
contracts/governance/locking/LockingVotes.sol
test/fork/ForkTests.t.sol
test/fork/upgrades/LockingUpgradeForkTest.sol
test/integration/governance/GovernanceIntegration.t.sol
test/unit/governance/GovernanceFactory.t.sol
test/unit/governance/Locking/Locking.fuzz.t.sol
test/unit/governance/Locking/LockingTest.sol
test/unit/governance/Locking/locking.upgrade.t.sol
test/unit/governance/Locking/relock.t.sol
test/utils/harnesses/LockingHarness.sol

Merge the latest changes from develop to main for the latest release (v2.6.2)
N/A

Release v2.6.2

---

test/fork/ForkTests.t.sol

This change updates the fork tests to include the newly created exchange for cUSD/cGHS
None
Ran the fork tests locally

test: update fork tests for cGHS

---

contracts/tokens/StableTokenGBPProxy.sol
contracts/tokens/StableTokenJPYProxy.sol
contracts/tokens/StableTokenNGNProxy.sol
contracts/tokens/StableTokenZARProxy.sol
test/unit/governance/Locking/LibBrokenLine.t.sol

Add the StableTokenXXXProxy contract for GBP, JPY, NGN and ZAR

feat: add proxies for GBP, JPY, NGN and ZAR

---

.github/workflows/storage-layout.yaml
contracts/governance/deployers/LockingDeployerLib.sol
contracts/governance/locking/Locking.sol
contracts/governance/locking/LockingBase.sol
contracts/governance/locking/LockingRelock.sol
contracts/governance/locking/LockingVotes.sol
contracts/tokens/StableTokenGBPProxy.sol
contracts/tokens/StableTokenJPYProxy.sol
contracts/tokens/StableTokenNGNProxy.sol
contracts/tokens/StableTokenZARProxy.sol
test/fork/ForkTests.t.sol
test/fork/upgrades/LockingUpgradeForkTest.sol
test/integration/governance/GovernanceIntegration.t.sol
test/unit/governance/GovernanceFactory.t.sol
test/unit/governance/Locking/LibBrokenLine.t.sol
test/unit/governance/Locking/Locking.fuzz.t.sol
test/unit/governance/Locking/LockingTest.sol
test/unit/governance/Locking/locking.upgrade.t.sol
test/unit/governance/Locking/relock.t.sol
test/utils/harnesses/LockingHarness.sol

New release after adding the new StableTokenXXX proxy contracts so that we can use them in mento-deployment https://github.com/mento-protocol/mento-core/pull/580
It seems like I messed up the release when I did v2.6.2 since the diff shows some commits that should have been merged as part of https://github.com/mento-protocol/mento-core/pull/578. Actual diff should only be https://github.com/mento-protocol/mento-core/commit/0ca06764811c6851d5cc276dc888a811a6a6b617

Release v2.6.3

---

contracts/tokens/TempStable.sol
test/fork/ForkTests.t.sol
test/fork/GHSRenameForkTest.sol

New release that includes the following:
https://github.com/mento-protocol/mento-core/pull/584 - Add temp implementation to change GHS name

Release v2.6.4

---

contracts/tokens/StableTokenAUDProxy.sol
contracts/tokens/StableTokenCADProxy.sol
contracts/tokens/StableTokenCHFProxy.sol

This adds the remaining G7 currencies proxies as proposed in https://forum.celo.org/t/launch-new-mento-stablecoins-jpy-gbp-aud-cad-chf-ngn-zar/10603

feat: add CHF, CAD and AUD proxies

---

test/fork/ForkTests.t.sol

Update the number of exchanges to include the three new pools for CHF, NGN and JPY

test: update alfajores fork tests to incl. CHF, NGN and JPY
