contracts/BiPoolManager.sol
contracts/interfaces/IBiPoolManager.sol
test/BiPoolManager.t.sol
test/Exchange.t.sol

Updated IBiPoolManager config variables 
- removed bucket0MaxFraction 
- removed tests that tested bucket0MaxFraction
- renamed bucketUpdateFrequency to referenceRateResetFrequency
- renamed bucket0TargetSize to stablePoolResetSize
- Fixes #24

refactor: pool config variables

---

contracts/Exchange.sol
contracts/ExchangeBRL.sol
contracts/ExchangeEUR.sol
contracts/interfaces/IExchange.sol
test/Exchange.t.sol

hotfix: revert codebase to StableToken bucket cap 
- cherry-picked Ninas [commit](https://github.com/mento-protocol/mento-core/pull/45/commits/0850ada75fa5f8b51efe51ff91ca582999fdb98f) from develop to also apply changes on main
- Fixes #45

chore: revert codebase to pre StableToken bucket cap

---

test/gas/BrokerGas.t.sol
test/gas/ExchangeGas.t.sol
test/gas/GasComparison.md
test/integration/BrokerIntegration.t.sol

This PR adds a gas comparison between Exchange.sol and Broker.sol common single swaps. Broker.sol gas usage is estimated locally with foundry building on the integration tests. Exchange.sol gas usage is estimated with fork testing from Celo mainnet. 
I created a Markdown file as a runbook on how to compare gas usage for future feature additions.
-
All tests pass.
- Fixes #33 
Fully
`GasComparison.md` in `/test/gas/`

feat: gas comparison

---

contracts/Broker.sol
contracts/interfaces/IBroker.sol
test/Broker.t.sol
test/mocks/MockStableToken.sol

In this PR I'm introducing changes in `Broker.sol` making it possible to burn stables without permissions
n/a
Unit tests to check everything works as expected
- Fixes #58 
should be backwards compatible

feat(broker): add burnstabletokens method

---

test/gas/GasComparison.md
test/utils/IntegrationSetup.sol

Adding trading limits to Broker integration tests and gas estimation
None
Yup all tests pass
- Fixes #33 
Fully
Nope

feat(test): update integration tests to config and use trading limits

---

contracts/Broker.sol
contracts/Reserve.sol
contracts/interfaces/IReserve.sol
test/Reserve.t.sol
test/mocks/MockReserve.sol
test/utils/IntegrationSetup.sol

In this pr, I'm updating a missing functionality in reserve, which will enable the broker to transfer collateral assets without being an object to spending limits
unit tests
- Fixes #79 
n/a
n/a

feat(reserve): allow limitless transfer of collateral assets

---

contracts/BreakerBox.sol
contracts/MedianDeltaBreaker.sol
contracts/interfaces/IBreaker.sol
contracts/interfaces/IBreakerBox.sol
test/BreakerBox.t.sol
test/MedianDeltaBreaker.t.sol
test/utils/IntegrationSetup.sol

Currently, the BreakerBox has an array of registered breakers. When a new price is reported, the breaker iterates through the list and checks each breaker for the rateFeedID. This means that there is no way to configure a breaker that's only checked for one rateFeed. At the same time, the existing MedianDeltaBreaker has a global priceChangeThreshold which is checked for all rates. The goal of this pr is to make this system more configurable.
Renamed priceChange to rateChange in the MedianDeltaBreaker and tests to keep things consistent.
Unit tests
- Fixes #81 
n/a

feat(breaker): make breakers configurable for specific ratefeeds

---

contracts/Broker.sol
contracts/Reserve.sol

Use SafeERC20 transfer functions.
None
- Unit tests run and pass as before
- Closes #103 
N/A
N/A

fix: use safeerc20 for transfers

---

contracts/BreakerBox.sol
contracts/Reserve.sol
test/Reserve.t.sol

Update to initialize local variables.
- Updated reserve to store remaining collateralAssetSpendingLimit 
- Unit tests run and pass as before
- Added tests to cover transfers that hit spending limit for collateral assets
- Closes #104 
N/A
N/A

fix: initilize local variables

---

contracts/Reserve.sol
test/Reserve.t.sol

In this pr, I've added a check in `removeSpender()` to verify that the spender exists before proceeding to try and remove it  in order to avoid unnecessary gas costs. 
Refactored existing `removeSpender()` test 
Unit test added
- Fixes [#143](https://github.com/mento-protocol/mento-general/issues/143)
Should be backwards compatible
n/a

feat: verify that spender exists before removing and refactor test

---

contracts/Reserve.sol

Removed unnecessary nonReentrant modifiers in `addToken()` and `addOtherReserveAddress()` functions
n/a
n/a
- Fixes [#147](https://github.com/mento-protocol/mento-general/issues/147)
Should be backwards compatible
n/a

fix: unnecessary nonReentrant modifiers

---

contracts/Broker.sol
contracts/interfaces/IBroker.sol
test/Broker.t.sol

- Added a missing event in `Broker.sol` in `configureTradingLimit()` function. 
- Ignored the changes requested in `StableTokenRegistry.sol`, because the contract has never been deployed and has been removed from the main branch.
n/a
Updated unit tests in `Broker.t.sol` to verify that everything works as expected.
- Fixes [#142](https://github.com/mento-protocol/mento-general/issues/142)
n/a
n/a

feat: added a missing event in Broker

---

contracts/SortedOracles.sol
test/SortedOracles.t.sol

- This change adds a zero address check when setting the breaker box
N/A
- Added test to verify check works
- Closes https://github.com/mento-protocol/mento-general/issues/146
N/A
N/A

refactor: add zero address check

---

contracts/BiPoolManager.sol
test/BiPoolManager.t.sol

Added a check in `BiPoolManager.sol` to verify that exchange can't be created with the same assets
n/a
Unit tests 
- Fixes [#144](https://github.com/mento-protocol/mento-general/issues/144)
n/a
n/a

feat: add a missing same asset check in BiPoolManager

---

contracts/StableToken.sol

- changed the order of division and multiplication for calculating the lastUpdate
- this increases precision because division gets truncated  
N/A
- calculated whether the new formula is equal to the old one
- all tests still pass
- Fixes https://github.com/mento-protocol/mento-general/issues/150
N/A
N/A

refactor: change division, multiplication order

---

contracts/Reserve.sol
test/Reserve.t.sol

When implementing our generalized `transferGold` to `transferCollateralAsset` method we skipped a critical check which constrained the logic only to allow transfers to addresses marked as `isOtherReserveAddress`.
This PR introduces this check back and updates the tests accordingly.
None
Tests are updated
N/A
No, but existing version was never released
N/A

fix: make transferCollateralAsset behaviour consistent with transferGold

---

test/BiPoolManager.t.sol
test/gas/BrokerGas.t.sol
test/gas/GasComparison.md
test/integration/BrokerIntegration.t.sol
test/utils/IntegrationSetup.t.sol

Rename `USDCet` to `bridgedUSDC`
N/A
N/A
N/A
N/A
N/A

fix: rename USDCet to bridgedUSDC

---

.github/workflows/ci.yml

- added a workflow that compares the storage layout of all proxy contract implementations and reverts PRs if they have changed
- The workflow uses  https://github.com/Rubilmax/foundry-storage-check to compare the storage between prior runs that are saved as artifacts.
- In order to perform this action on each of the proxy implementations the get_proxy_names  job creates a matrix containing all the contracts for which we want to check the storage 
- Once this branch is merged to develop it will fail on the first run since the artifacts don't exist yet and need to be built for the first time. 
- N/A
- In order to test this I created the test/new-ci-job branch that branches of the feature/add-storage-layout-check branch.
- After this opened a Pr and made changes to the Reserve.sol that …

feat: add storage layout workflow

---

contracts/interfaces/IBreakerBox.sol
contracts/oracles/BreakerBox.sol
contracts/oracles/breakers/MedianDeltaBreaker.sol
contracts/oracles/breakers/ValueDeltaBreaker.sol
test/gas/BrokerGas.t.sol
test/integration/ConstantSumIntegration.t.sol

Minor updates to some of the comments to use consistent language.
- None
- N/A 
- None
- N/A
- N/A

chore: update comments

---

test/fork-tests/BaseForkTest.t.sol
test/fork-tests/TestAsserts.t.sol
test/fork-tests/Utils.t.sol

This fixes the fork tests which were broken after the many changes done in MU03, mainly the stuff around EMA in the MedianDeltaBreaker, the constantSum pricing module, and the breakerBox refactor.
While working on this we also realized that we forgot to update the breakerBox implementation in the biPoolManager, so god bless the fork tests 🙏 
- Added tests for dependent rate feeds
- Small refactors/added additional comments for context here and here
Fork tests are green
> Test result: ok. 18 passed; 0 failed; finished in 116.26s
✨  Done in 129.74s.
Fixes https://github.com/mento-protocol/mento-general/issues/295
-
-

fix: outdated fork-tests after MU03

---

test/fork-tests/BaseForkTest.t.sol
test/fork-tests/TestAsserts.t.sol
test/fork-tests/Utils.t.sol
test/utils/TokenHelpers.t.sol

Fork tests weren't passing on `baklava` after the eXOF update because:
1. We have an unrecoverable breaker
2. We have trading limits on both assets in a pool
3. We have multiple dependencies on a single rate
The approaches I took to fix were:
1. Include manual reset logic to our helper functions that used to reset breakers just by altering the median
2. Check if both assets have limits and in that case choose to test the limit that is more restrictive
3. Slightly alter the logic for rate feed dependencies to test when there are multiple dependencies for a rate feed.
For (3) I initially tried an approach where I was using low-level `call` to figure out how many dependencies a rate feed has but that threw me into a rabbit hole of weird foundry behaviour because catching those `call` reverts …

Update fork tests to work with eXOF

---

contracts/tokens/StableTokenV2.sol
test/tokens/StableTokenV2.t.sol

While testing MU04 on Baklava we noticed that gas payment with stables was broken and after some digging we realized that this is due to a slight change in the implementation details of the `creditGasFees` function after switching to the StableTokenV2 implementation. 
TL;DR is that there were checks for the null address in the v1 implementation that were removed in v2, which makes the tx fail when the node attempts to include it in a block due to the `gatewayFeeRecipient` address being `0x` and the underlying call to `_transfer(from, 0x, amount)` failing. 
This change adds a null address check for each recipient addresses and it also keeps track of any amount that can't be transferred to recipients so that it's burned at the end of the function for proper accounting purposes.
Fixed a …

fix: add null addresses checks in creditGasFees

---

test/fork-tests/BaseForkTest.t.sol
test/gas/ExchangeGas.t.sol
test/utils/TokenHelpers.t.sol

This updates the fork-tests to work post MU04 execution on Baklava. It did required a bit but debugging the overall changes ended up being quite small:
- Minting more collateral to the Reserve address (since trading limits will be higher)
- Update the contract already initialized message for StableTokenV2
- ~Remove the old mint functions for the v1 stable tokens~ 
update: ended up bringing it back as it's needed for a gas test that runs on mainnet
Fork tests are green on Baklava ✅
```
Running 18 tests for test/fork-tests/EnvForkTest.t.sol:BaklavaForkTest
[PASS] test_biPoolManagerCanNotBeReinitialized() (gas: 38850)
[PASS] test_brokerCanNotBeReinitialized() (gas: 19360)
[PASS] test_circuitBreaker_breaks() (gas: 72145240)
[PASS] test_circuitBreaker_haltsTrading() (gas: 77095231)
[PASS] …
```

fix: update fork-tests after MU04

---

contracts/governance/locking/LockingBase.sol
test/governance/Locking/locking.t.sol

Currently the starting point of the week is Friday 00:00 UTC. It is decided that it will be better to start the week at 00:00 Wednesday, in the middle of the week.
The PR updates the epoch shift to move the start of the week.
No
Updated the current unit test
- Fixes #287

Feat: Shift locking week

---

test/governance/IntegrationTests/GovernanceIntegration.t.sol
test/governance/IntegrationTests/Proposals.sol
test/utils/VmExtension.sol

refactor: make Proposal a library, and turn Utils in VmExtension

---

contracts/common/ICeloGovernance.sol

function type is wrong for the interface and causes to send a tx instead of a view call
none

fix: function type minDeposit

---

contracts/common/ICeloGovernance.sol
contracts/governance/GovernanceFactory.sol

Small changes required for governance deployment:
1- Adding `execute` and `dequeued` to Celo Governance interface because we need to execute the proposal manually with a custom gas limit. 
2- Storing `airgrabEnds` value in the factory contract because that value is required to verify airgrab contract.
No
Previous tests still pass

feat: store airgrabEnds in factory

---

contracts/governance/GovernanceFactory.sol
test/governance/GovernanceFactory.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

When we moved to a dynamic initial allocation calculation, we did something that has the potential for confusion: we're passing in two arrays to the GovernanceFactory contract:
- additionalAllocationRecipients
- allocationAmounts
With the implicit idea that `allocationAmounts.length == additionalAllocationRecipients.length + 2` and that the first two `allocationAmounts` relate to the airgrab and the Mento Treasury.
Even tho this is a one time thing I find that this adds the potential for confusion and will also make reviews more complicated.
I propose simplifying this by introducing an initial allocation struct:
```solidity
struct MentoTokenAllocationParams {
uint256 airgrabAllocation;
uint256 mentoTreasuryAllocation;
address[] additionalAllocationRecipients;
uint256[] …
```

feat: Improve how the initial allocation is forwarded.

---

contracts/governance/GovernanceFactory.sol
contracts/governance/MentoToken.sol
contracts/governance/deployers/MentoTokenDeployerLib.sol
test/governance/MentoToken.t.sol

Based on recent token-related conversations we've decided we want more flexibility when it comes to the time between when we launch governance and give utility to the token, and the time when the token is transferable, i.e. tradable.
Most recent token launches have followed this approach, most notably Safe.
These changes make the token ownable and pausable. 
However, even when paused the token can still be transferred by:
- The owner
- The locking contract - it can be locked and unlocked, thus the airgrab can run while paused
- The emissions contract - it can be minted into existence while paused
N/A
- Tests have been added for the paused scenario
N/A
N/A

feat: make Token pausable

---

contracts/governance/locking/LockingBase.sol
test/governance/Airgrab.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol
test/governance/IntegrationTests/LockingIntegration.fuzz.t.sol
test/governance/Locking/delegateTo.t.sol
test/governance/Locking/locking.t.sol
test/governance/Locking/relock.t.sol
test/tokens/StableTokenV2.t.sol

Currently the voting power formula looks like this (slightly simplified):
```math
P(t,s,c) = t * (0.2 + 0.8 * c / c_{max} + 0.6 * s / s_{max})
```
We want to bring the system closer to the classical veCurve formula, by changing it to:
```math
P(t,s,c) = t * min(s/s_{max} + c/c_{max}, 1)
```
More details can be seen here https://github.com/mento-protocol/mento-core/issues/373
Since this formula sits in the core of the voting power calculations, reviews should be on a broader level. Please go through code changes, test calculations and more importantly how this may affect the whole locking mechanism.
Known issues:
- users can lock with a suboptimal schedule if the summed multiplier goes above 1. 
Updated the tests to use the exact amounts and not approximations
Removed unused imports
Fixed …

Update locking formula

---

.github/workflows/storage-layout.yaml

CI job that checks storage layouts are failing because we moved SortedOracles to common directory but did not update the path in the job.
This PR aims to fix that by updating the path
no
N/A
- Issue not tracked

chore: fix path to sorted oracles

---

contracts/governance/Emission.sol
contracts/governance/GovernanceFactory.sol
test/governance/Emission.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

We forgot to update hardcoded emission supply in the emission contract after making allocations parametrised. This may cause issues with the emission calculation when the emission supply in the token contract is not equal to the hardcoded emission supply in the emission contract.
This fix removes the hardcoded emission supply, and sets it through init call from the governance factory.
No
Fixed unit tests
- Fixes #395

fix: hardcoded emission supply

---

contracts/governance/Airgrab.sol
test/governance/Airgrab.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

Update the KYC credentials to required level(plus) and expected countries(DRC, CUBA, GB, IRAN, DPKR, MALI, MYANMAR, SOUTH SUDAN, SYRIA, US, YEMEN)
Blacklisted regions that are not countries will be blocked by fractal using an exception
No
- Current tests are updated
- Signature that returns from fractal is verified to work with the updated claim function
- It will be tested with forked-integration tests after a new deployment
- Fixes [291](https://github.com/mento-protocol/mento-core/issues/291)

feat: new kyc criteria

---

contracts/governance/Airgrab.sol
contracts/governance/GovernanceFactory.sol
contracts/governance/deployers/AirgrabDeployerLib.sol
test/governance/Airgrab.t.sol
test/governance/GovernanceFactory.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol
test/governance/IntegrationTests/LockingIntegration.fuzz.t.sol

this Pr updates the airgrab contract + the GovernanceFactory to use the governanceTimelock(Mento Treasury) instead of the celo community fund for the refund address of unclaimed airgrab tokens.  
Will open a Pr for the deployment repo changes once this Pr is merged. 
updated tests to test the new behavior 
- Fixes #401 
wasn't able to find where the Mento Governance Diagram comes from will update the diagram once i know

feat: update airdrop refund address to Mento Treasury

---

contracts/governance/locking/Locking.sol
contracts/governance/locking/LockingBase.sol
contracts/governance/locking/LockingRelock.sol
test/governance/Locking/locking.t.sol

This PR removes stop functionality from locking contracts to fix Sherlock contest finding [14](https://github.com/sherlock-audit/2024-02-mento-judging/issues/14)
Main reason why we decided to remove it altogether instead of applying the fixes is, after a stop, balanceOf returns 0 for all accounts, which might cause bricking the whole governance.
No
- Removed related unit tests
- Fixes #406

feat: remove stop and start

---

contracts/governance/locking/LockingBase.sol

This removes the `setStartingPointWeek` function since it no longer will be used anyhow after we removed the migration related code.
- Fixes https://github.com/mento-protocol/mento-core/issues/408

fix: remove setStartingPointWeek

---

contracts/governance/GovernanceFactory.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

This updates the airgrab duration to `8 weeks` (confirmed with @olenovyk that this will be exactly 56 days).
Note: the slither issues are not from this PR so please ignore those in the meantime. We'll fix those once we merge https://github.com/mento-protocol/mento-core/tree/fix-contest-findings-fixes-review into develop.
Updated the existing unit tests and it will also be covered by integration tests + deployment checks 
Related to https://github.com/mento-protocol/mento-core/issues/405

fix: update airgrab duration

---

contracts/governance/GovernanceFactory.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

There was a bit of back and forth on this and at the end it was decided that the airgrab duration will be increased to 10 weeks (from the current 8 weeks).
Updated the existing unit tests
- Fixes https://github.com/mento-protocol/mento-core/issues/417

fix: update airgrab duration to 10 weeks

---

contracts/governance/GovernanceFactory.sol
test/governance/IntegrationTests/GovernanceIntegration.gas.t.sol
test/governance/IntegrationTests/GovernanceIntegration.t.sol

While going through governance config, we decided it will be better to start with a higher proposal threshold to prevent spam and decided 10_000 veMENTO would be a good start.
There is another PR that updates the threshold in post deployment checks:
https://github.com/mento-protocol/mento-deployment/pull/183
Fork tests will be fixed once we have a new deployment.
No
Updated some tests with larger lock amounts to pass the new threshold
- Fixes #430

feat: update proposal threshold

---

foundry.toml

The verbosity setting for CI tests was set to `4`, which outputs full stack traces for all (even passed) tests. This leads to extremely verbose output that doesn't get fully displayed in GitHub UI (need to download a 52MB, 350k line log file). This makes it more time consuming to pinpoint what specific tests are causing the workflow to fail. [Example](https://github.com/mento-protocol/mento-core/actions/runs/9779856065/job/27000074200?pr=456).
I propose we set verbosity to `3`, which should still output stack traces for failing tests. The one thing missing will be setup traces for failing tests, but this should still be a quality of life improvement.
Nothing, this is a one byte change.
Will need to look at CI output for this PR.

chore: reduce CI foundry test verbosity

---

test/fork-tests/BaseForkTest.t.sol

This modifies the list of hardcoded collateral assets to add USDT so that the fork-tests pass after MU06.
N/A
MU06 is deployed on Baklava and fork tests are green
```bash
Ran 18 tests for test/fork-tests/EnvForkTest.t.sol:BaklavaForkTest
[PASS] test_biPoolManagerCanNotBeReinitialized() (gas: 38850)
[PASS] test_brokerCanNotBeReinitialized() (gas: 19360)
[PASS] test_circuitBreaker_breaks() (gas: 120622552)
[PASS] test_circuitBreaker_haltsTrading() (gas: 132297226)
[PASS] test_circuitBreaker_rateFeedsAreProtected() (gas: 1152356)
[PASS] test_circuitBreaker_recovers() (gas: 42665936)
[PASS] test_rateFeedDependencies_haltsDependantTrading() (gas: 52617076)
[PASS] test_reserveCanNotBeReinitialized() (gas: 19309)
[PASS] test_sortedOraclesCanNotBeReinitialized() (gas: 16489)
[PASS] …
```

fix: add nativeUSDT to collateral assets

---

contracts/interfaces/IChainlinkRelayerFactory.sol
contracts/oracles/ChainlinkRelayerFactory.sol
test/integration/ChainlinkRelayerIntegration.t.sol
test/oracles/ChainlinkRelayerFactory.t.sol

We realised that it would be better operationally to separate the proxy ownership ACL from the deployer ACL, that way we can keep using the `mento-deployer` account for relayer deploy, and use the multisig only for proxy updates.
N/A
Tests added
N/A
No, but no mainnet deployment yet.
N/A

feat: Add relayerDeployer ACL role to the factory

---

contracts/interfaces/IChainlinkRelayer.sol
contracts/interfaces/IChainlinkRelayerFactory.sol
contracts/oracles/ChainlinkRelayerFactory.sol
contracts/oracles/ChainlinkRelayerV1.sol
test/integration/ChainlinkRelayerIntegration.t.sol
test/oracles/ChainlinkRelayerFactory.t.sol
test/oracles/ChainlinkRelayerV1.t.sol

This reverts commit ac1c5406441c01119eaf9c0de54512f7cfe1ff19.
Brings back the maxTimestampSpread setting. A visual explanation here:
We need it because CELO/USD has a heartbeat of 24hr and PHP/USD 5minutes, therefore we could be in a situation where the spread between reports is quite large, and if we rely only on max timestamp spread we could be reporting with stale data. The rule of thumb is:
- Set `maxTimestampSpread` by considering the largest heartbeat frequency.
- Set `tokenExpiry` in SortedOracles by considering the shortest heartbeat frequency.
N/A
Yup
N/A
N/A
N/A

Revert "feat: remove maxTimestampSpread and only rely on expiry"

---

.github/workflows/slither.yaml
.github/workflows/storage-layout.yaml

CI is currently red on `develop` because I forgot to remove these old contracts from the storage-layout check in CI, and that only happens on push to develop and PR to main (for artifact rate limiting reasons). This PR removes them from the job.
I've also reenabled `continue-on-error` on slither because it makes it nicer to work with via the sarif file. In the past we've disabled it because we were hitting the rate-limit on artifact upload and that ended up being a false-nagative failure mode, but that was before we moved the storage-layout check to develop and main only and that was the main hog. We didn't reenable it after doing that but I think now would be a good time to see if it works.
If you need to bring it back revert this commit: 754c8be
Yes
N/A
YES
N/A

chore: remove contracts that we no longer manage from storage-layout checks

---

foundry.toml
test/integration/governance/GovernanceIntegration.gas.t.sol

Context: We create 50k locks to check how much gas is used by governance and locking operations for users with high number of locks. It was working fine until a couple of weeks ago. Then we disabled the gas tests to make CI happy.
The problem was related to a [recent change on foundry](https://github.com/foundry-rs/foundry/pull/8274/files). They reduced the default gas limit for tests from `9223372036854775807` to `1073741824` which is not enough to create as many locks as we want.
This PR fixes the issue by setting the gas limit to the previous default value of `9223372036854775807` or `i64::MAX / 2` and re-enables the gas tests. I don't think this will cause any problems as the only downside of this is if we have an infinite loop in our tests, it will take some time to consume all the …

fix: gas tests

---

test/fork/ForkTests.t.sol

update Alfajores exchange count + test for new PUSO exchange post-PUSO execution
fork test are green again

test: add fork test for new PUSO exchange

---

contracts/swap/Broker.sol
test/unit/swap/Broker.t.sol

This Pr adds a check on Broker quotes ensuring that if the TokenOut is a collateral asset the reserve can match the amountOut if not the call reverts. 
fixed the test + added additional unit tests 
- Fixes https://github.com/mento-protocol/mento-general/issues/554

feat: add Broker liquidity check

---

contracts/goodDollar/BancorExchangeProvider.sol
contracts/goodDollar/GoodDollarExchangeProvider.sol
contracts/goodDollar/GoodDollarExpansionController.sol
contracts/goodDollar/interfaces/IGoodProtocol.sol
contracts/interfaces/IBancorExchangeProvider.sol
contracts/interfaces/IBiPoolManager.sol
contracts/interfaces/IBroker.sol
contracts/interfaces/IExchangeProvider.sol
contracts/interfaces/IGoodDollarExchangeProvider.sol
contracts/interfaces/IGoodDollarExpansionController.sol
contracts/swap/Broker.sol
test/unit/goodDollar/BancorExchangeProvider.t.sol
test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
test/unit/goodDollar/GoodDollarExpansionController.t.sol

Fixes https://github.com/mento-protocol/mento-general/issues/552

Streamline comments and errors

---

test/fork/BaseForkTest.sol
test/fork/ForkTests.t.sol
test/unit/goodDollar/GoodDollarExchangeProvider.t.sol

feat: add cCOP fork tests

---

contracts/goodDollar/BancorExchangeProvider.sol
test/unit/goodDollar/BancorExchangeProvider.t.sol

This PR ensures that the exit contribution is set to a value smaller 100%. 
updated test to ensure setter fails on exitContribution of 100%
[https://github.com/mento-protocol/mento-general/issues/600](https://github.com/mento-protocol/mento-general/issues/600)

feat: ensure exitContribution is less than 100%

---

contracts/goodDollar/GoodDollarExpansionController.sol

remove unused pausable
test are still green
https://github.com/mento-protocol/mento-general/issues/599
contract was unused functionalities can be paused from the G$ ExchangeProvider

chore: remove Pausable

---

contracts/goodDollar/BancorExchangeProvider.sol

This PR removes a redundant require check which is already present in the next step of the function
`forge test` 
- Fixes [#603](https://github.com/mento-protocol/mento-general/issues/603)

fix: Removed redundant require

---

contracts/goodDollar/GoodDollarExchangeProvider.sol
test/unit/goodDollar/GoodDollarExchangeProvider.t.sol

This PR addresses the reward ratio reaching 0 if the reward is a large enough number
`forge test ./test/unit/goodDollar/GoodDollarExchangeProvider.t.sol `
- Fixes [#595](https://github.com/mento-protocol/mento-general/issues/595)

fix: $GD resolved large reward issue

---

contracts/goodDollar/BancorExchangeProvider.sol

This PR fixes a redundant casting of an address 
- Fixes [#604](https://github.com/mento-protocol/mento-general/issues/604)

fix: Typo redundant casting

---

contracts/goodDollar/GoodDollarExpansionController.sol
test/unit/goodDollar/GoodDollarExpansionController.t.sol

This PR adds scaling to the reserve balance read in mintUBIFromReserveBalance in Case the token has less than 18 decimals.
- added test verifying expected behavior for token with 6 decimals

fix: ensure scaling for different reserveAsset token decimals

---

contracts/goodDollar/GoodDollarExpansionController.sol
test/unit/goodDollar/GoodDollarExpansionController.t.sol
test/utils/harnesses/GoodDollarExpansionControllerHarness.sol

fixes issue in how lastUpdated was set:
before if  3.5 days passed and a daily expansion was configured, 3 expansions were calculated and the last expansion timestamp was updated to now essentially losing half a day. Over time this could have resulted in the yearly expansion rate not being achieved. 
-  added tests for this behavior 
https://github.com/mento-protocol/mento-general/issues/592

fix: setting of last expansion timestamp

---

contracts/goodDollar/GoodDollarExchangeProvider.sol
contracts/goodDollar/GoodDollarExpansionController.sol
contracts/interfaces/IGoodDollarExchangeProvider.sol
contracts/interfaces/IGoodDollarExpansionController.sol
test/unit/goodDollar/GoodDollarExchangeProvider.t.sol
test/unit/goodDollar/GoodDollarExpansionController.t.sol
test/utils/harnesses/GoodDollarExpansionControllerHarness.sol

Adds slippage protection to `updateRatioForReward()`
Simplifies the new ratio calculation formula
Unit tests
- Fixes [#594](https://github.com/mento-protocol/mento-general/issues/594)

Feat: slippage protection for reserve ratio

---

contracts/goodDollar/BancorExchangeProvider.sol
test/unit/goodDollar/BancorExchangeProvider.t.sol

This PR adds a check to prevent exchanges with zero reserve being created.
This rendered 4 tests redundant due to an exchange of this nature not being possible at creation
- Fixes [#602](https://github.com/mento-protocol/mento-general/issues/602)

Fix: Exchange created with zero reserve

---

contracts/goodDollar/BancorExchangeProvider.sol
test/unit/goodDollar/BancorExchangeProvider.t.sol

Scales down the current price to correct decimals dividing it by the reserve asset precision multiplier
added some extra tests for swapIn and swapOut with non standard token decimals
Unit test
- Fixes #559

fix: update currentPrice to return correct decimals

---

contracts/goodDollar/BancorExchangeProvider.sol
test/unit/goodDollar/BancorExchangeProvider.t.sol

This PR ensures that amountOut's returned are always rounded down when tokenPrecisionMultipliers are applied and amountIn's are always rounded up. The rounding down of amountOut's was already done through the division by tokenPrecisionMultipliers the same was done to the the amountIn. This meant that when a token has less than 18 decimals the amountIn was wrongly scaled down -> returning a better price than what the calculation returned.
This has been changed by adding a new `divAndRoundUp` function. The function adds a +1 when the amountIn is scaled down to a different decimal precision and decimals are lossed.
- added tests that verify we also do the rounding down correctly for amountOut. 
- new tests added for both getAmountIn and swapOut …

feat: ensure amountOut's are rounded down and amountIn's are roundedUp

---

test/fork/upgrades/LockingUpgradeForkTest.sol

Locking Upgrade fork tests were failing because:
1. Locking proxy admin is owned by the multisig now
2. A subtle issue in how we handle timetraveling causing problems with brokenLine internals because we fork the current block's state, roll back to Nov 7 roll forward 3 weeks and make calculations for the month December. Which causes brokenLine.update to try updating the line for a past time if you run the test after December. (kudos to @philbow61)
This PR fixes the tests by setting up the fork test correctly and moving 30 weeks into future before starting tests 
_calculateBlocksTillNextWeek uses values from the contract now

Fix locking upgrade fork test

---

contracts/governance/locking/LockingRelock.sol
test/unit/governance/Locking/relock.t.sol

[Hats issue #10](https://github.com/hats-finance/Mento-0x2a1b9b1f6fa7c2e73815a7dff0e1688767382694/issues/10) identified that in the event of relocking a completed lock, there was no minimum check that was present in a standard lock, this was given the assumption that relocking would only occur on non expired locks.

Fix: Relocking min amount bypass

---

contracts/governance/deployers/LockingDeployerLib.sol
contracts/governance/locking/Locking.sol
test/fork/upgrades/LockingUpgradeForkTest.sol
test/integration/governance/GovernanceIntegration.t.sol
test/unit/governance/GovernanceFactory.t.sol
test/unit/governance/Locking/Locking.fuzz.t.sol
test/unit/governance/Locking/LockingTest.sol
test/utils/harnesses/LockingHarness.sol

This PR addresses the implementation having an exposed and callable, however without any structural risk, initializer in future implementations of the Locking contract

Feat: Disable Initializer

---

test/fork/upgrades/LockingUpgradeForkTest.sol
test/unit/governance/Locking/LibBrokenLine.t.sol

New locking implementation is deployed and currently used by the Locking proxy on the mainnet. Also Celo L2 transition block no is announced.
This PR udpates the L2 fork tests to use the announced block number and calculated l2 starting point week and epoch shift.
Go through the fork tests, ensure the changes introduced make sense and tests still pass, confirm the l2 starting point week and epoch shift.(epoch shift assumes there won't be down time)
Forge v1.0 breaking changes addressed
Fork tests

Test l2 changes with announced blockno and deployed locking impl

---

test/fork/ForkTests.t.sol

This updates the fork tests on Alfajores to include the new pools from the FX01 proposal
Ran them on Alfajores
> Ran 23 test suites in 69.63s (672.74s CPU time): 303 tests passed, 0 failed, 0 skipped (303 total tests)
✨  Done in 85.52s.

test: update alfajores fork tests to incl. cGBP, cZAR, cAUD and cCAD

---

test/fork/BaseForkTest.sol
test/fork/ExchangeForkTest.sol
test/fork/ForkTests.t.sol

This fixes the alfajores fork tests after executing the pool restructuring CGP. We now have 19 total exchanges, and a new dependency on the XOF/USD feed.

fix: alfajores fork tests post pool restructuring
